# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import recifegrafica.arts_and_orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_and_orders', '0002_auto_20170130_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=recifegrafica.arts_and_orders.models.user_directory_path, verbose_name=b'Arquivo da arte'),
        ),
    ]
