# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-31 18:05
from __future__ import unicode_literals

from django.db import migrations
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20150604_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['date_created', 'pk'], 'verbose_name': 'Basket line', 'verbose_name_plural': 'Basket lines'},
        ),
        migrations.AlterField(
            model_name='line',
            name='line_reference',
            field=oscar.models.fields.slugfield.SlugField(max_length=128, verbose_name='Line Reference'),
        ),
    ]
