# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20170131_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='art_file',
            field=models.FileField(blank=True, null=True, upload_to=b'documents/%Y/%m/%d'),
        ),
    ]
