# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20170131_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='document',
            field=models.FileField(null=True, upload_to=b'teste', verbose_name=b'Arquivo da arte'),
        ),
    ]
