# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_line_document'),
        ('basket', '0007_line_art_file'),
    ]

    operations = [
    ]
