# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_remove_line_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='art_file',
            field=models.FileField(blank=True, null=True, upload_to=b'documents/%Y/%m/%d', verbose_name=b'Arquivo de arte'),
        ),
    ]
