# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20170203_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='art_file',
            field=models.FileField(blank=True, null=True, upload_to=b'Temp/', verbose_name=b'Arquivo de arte'),
        ),
    ]
