# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_auto_20170206_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='hire_art',
            field=models.NullBooleanField(verbose_name=b'Contratou servi\xc3\xa7o de arte?'),
        ),
    ]
