# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_auto_20170206_1514'),
        ('basket', '0013_auto_20170206_1719'),
    ]

    operations = [
    ]
