# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import recifegrafica.order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_line_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='document',
            field=models.FileField(null=True, upload_to=recifegrafica.order.models.user_directory_path, verbose_name=b'Arquivo da arte'),
        ),
    ]
