# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170201_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='document',
            new_name='art_file',
        ),
    ]
