# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-06 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20170206_1641'),
        ('order', '0009_auto_20170206_1514'),
    ]

    operations = [
    ]
